# Generated by Django 4.0.3 on 2022-03-28 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_customuser_groups_customuser_user_permissions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_client',
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('client', 'client'), ('client_admin', 'client_admin'), ('staff', 'staff'), ('customer', 'customer')], default='cleint_admin', max_length=20),
            preserve_default=False,
        ),
    ]
