# Generated by Django 4.0.3 on 2022-03-28 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_alter_business_account'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='business',
            field=models.ForeignKey(max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, to='business.business'),
        ),
    ]
