# Generated by Django 4.0.3 on 2022-03-28 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_product_stock_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit_increment',
            field=models.CharField(help_text='Unit of increment while adding to card, EG: 0.5, 1', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit_measurement',
            field=models.CharField(help_text='Unit of measuring the item EG: grams, module, etc.. ', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
    ]
