# Generated by Django 4.0.3 on 2022-03-30 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stock_unit',
            field=models.IntegerField(default=0, help_text='Quantity remaining in stock'),
        ),
    ]
