# Generated by Django 4.0.3 on 2022-03-27 21:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('system_settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('business_name', models.CharField(max_length=255, unique=True)),
                ('last_payment_date', models.DateTimeField(auto_now_add=True)),
                ('next_payment_date', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system_settings.package')),
            ],
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('store_name', models.CharField(max_length=255, unique=True)),
                ('address', models.CharField(max_length=255)),
                ('account_id', models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, to='business.account')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system_settings.country')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system_settings.state')),
            ],
        ),
    ]
