# Generated by Django 4.0.3 on 2022-03-28 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='account_id',
        ),
        migrations.AddField(
            model_name='business',
            name='account',
            field=models.ForeignKey(blank=True, default='c5a6ab25-07c1-418c-bf40-ac8178ed262a', max_length=50, on_delete=django.db.models.deletion.CASCADE, to='business.account'),
            preserve_default=False,
        ),
    ]
